version: '3'
services:
  teste-postgres-compose:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: Post
    ports:
      - "15432:5432"
    networks:
      - postgres-compose-network
    volumes:
      - db-data:/volume_data
networks:
  postgres-compose-network:
    driver: bridge

volumes:
  db-data:
    driver: local